button_card_templates: !include_dir_merge_named button_card_templates

views:
  - type: custom:grid-layout
    title: Home
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  varie       lights    tapparelle  ."
        "sidebar  media       climate   casa   ."
        "sidebar  footer      footer    footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  varie       tapparelle   ."
            ".  lights      climate   ."
            ".  media       casa    ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  varie       tapparelle  ."
            "sidebar  lights      climate  ."
            "sidebar  media       casa   ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:
      #extra_styles fix, do not remove
      #also warn if theme is not set

      - type: custom:button-card
        view_layout:
          grid-area: 1 / 2 / 2 / 5
        name: SET THEME TO "tablet" IN PROFILE
        tap_action:
          action: navigate
          navigation_path: /profile
        styles:
          card:
            - display: >
                [[[
                  return hass.themes.theme === 'tablet'
                      ? 'none'
                      : 'initial';
                ]]]
          name:
            - z-index: 1
            - overflow: visible
            - color: red
            - font-weight: bolder
            - font-size: xxx-large
            - background: yellow

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar

          - type: weather-forecast
            entity: weather.forecast_smv
            name: Torre Boldone
            show_forecast: false
            styles:
              card:
                - font-family: Sf Display
                - border-radius: var(--custom-button-card-border-radius)
                - -webkit-tap-highlight-color: rgba(0,0,0,0)
                - transition: none
                - padding: 11.5% 10.5% 10.5% 11.5%
                - background-color: rgba(115, 115, 115, 0.2)

          - type: custom:button-card
            name: Todo
            styles:
              card:
                - --ha-card-border-width: 0

          - type: custom:todoist-card
            entity: sensor.todo_list
            show_header: false
            show_completed: 0
            show_item_add: false
            show_item_close: true
            show_item_delete: false
            only_today_overdue: true
            show_days_count: 5
            min_priority_level: 3

          - type: custom:atomic-calendar-revive
            refreshInterval: 3600
            entities:
              - entity: calendar.stefano_calendar
                titleColor: red
              - entity: calendar.compleanni
                titleColor: blue
              - entity: calendar.famiglia
                titleColor: purple

      #################################################
      #                                               #
      #                     VARIE                     #
      #                                               #
      #################################################

      - type: grid
        title: Varie
        view_layout:
          grid-area: varie
        columns: 2
        cards:
          - type: custom:button-card
            entity: sensor.speedtest_download
            name: Download
            variables:
              max: 1000
              color: "#00f596"
            template:
              - speed

          - type: custom:button-card
            entity: sensor.speedtest_upload
            name: Upload
            variables:
              max: 100
              color: "#00f596"
            template:
              - speed

          - type: custom:button-card
            entity: media_player.lg_webos_smart_tv
            name: Tv
            state_display: >
              [[[
                if (variables.state === 'playing') {
                  return 'Riproduzione';
                }
                if (variables.state === true) {
                  return variables.translate_unknown;
                }
              ]]]
            double_tap_action: !include popup/varie_tv.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                    LIGHTS                     #
      #                                               #
      #################################################

      - type: grid
        title: Luci
        view_layout:
          grid-area: lights
        columns: 2
        cards:
          - type: custom:button-card
            entity: light.wiz_tunable_white_22045f
            name: Bagnetto
            template:
              - light
              - icon_hue
          - type: custom:button-card
            entity: light.wiz_rgbww_tunable_f361c9
            name: Cameretta
            template:
              - light
              - icon_hue

      #################################################
      #                                               #
      #                   TAPPARELLE                  #
      #                                               #
      #################################################

      - type: grid
        title: Tapparelle
        view_layout:
          grid-area: tapparelle
        columns: 2
        cards:
          - type: custom:button-card
            entity: cover.tutte_le_tapparelle
            name: Tutte
            template:
              - cover

          - type: custom:button-card
            entity: cover.tapparelle_zona_giorno
            name: Zona giorno
            template:
              - cover

          - type: custom:button-card
            entity: cover.tapparelle_zona_notte
            name: Zona notte
            template:
              - cover

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:
          - type: custom:swipe-card
            parameters:
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              - type: horizontal-stack
                cards:
                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state_not: LG webOS TV

                      - entity: select.conditional_media
                        state_not: Spotify

                      - entity: select.conditional_media
                        state_not: MiSmartClock
                    card:
                      type: custom:button-card
                      entity: camera.google_photos_favorites_media
                      tap_action:
                        action: none
                      template:
                        - conditional_media
                        - icon_google_photos

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: LG webOS TV
                    card:
                      type: custom:button-card
                      entity: media_player.lg_webos_smart_tv
                      template:
                        - conditional_media
                        - icon_tv

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: Spotify
                    card:
                      type: custom:button-card
                      entity: media_player.spotify_stefano_sonzogni
                      template:
                        - conditional_media
                        - icon_spotify

                  - type: conditional
                    conditions:
                      - entity: select.conditional_media
                        state: MiSmartClock
                    card:
                      type: custom:button-card
                      entity: media_player.mismartclock
                      template:
                        - conditional_media
                        - icon_nest_mini

              - type: grid
                columns: 2
                cards:
                  - type: custom:button-card
                    entity: media_player.lg_webos_smart_tv
                    triggers_update: sensor.youtube_watching
                    name: LG TV
                    template:
                      - media
                      - icon_tv

                  - type: custom:button-card
                    entity: media_player.spotify_stefano_sonzogni
                    name: Spotify
                    template:
                      - media
                      - icon_spotify

                  - type: custom:button-card
                    entity: media_player.mismartclock
                    name: Mi Smart Clock
                    template:
                      - media
                      - icon_nest_mini

      #################################################
      #                                               #
      #                   Climate                     #
      #                                               #
      #################################################

      - type: grid
        title: Clima
        view_layout:
          grid-area: climate
        columns: 2
        cards:
          - type: custom:button-card
            entity: climate.daikin_stylish_2
            name: AC soggiorno
            double_tap_action: !include popup/climate_soggiorno.yaml
            triggers_update:
              - fan.stylish_fan_only
            template:
              - base
              - icon_climate
              - climate
            variables:
              sensors:
                - sensor.daikin_stylish_inside_temperature
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state === 'cool' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

          - type: custom:button-card
            entity: climate.daikin_perfera
            name: AC camera
            double_tap_action: !include popup/climate_camera.yaml
            template:
              - base
              - icon_climate
              - climate
            variables:
              sensors:
                - sensor.daikin_perfera_inside_temperature
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state === 'cool' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

          - type: custom:button-card
            entity: fan.stylish_fan_only
            name: "Ventilatore"
            #double_tap_action: !include popup/climate_ventilatore.yaml
            triggers_update:
              - climate.daikin_stylish_2
            template:
              - base
              - icon_fan2
              - loader

          - type: custom:button-card
            entity: humidifier.deerma_jsq5_cf89_humidifier
            name: "Umidificatore"
            double_tap_action: !include popup/climate_humidifier.yaml
            template:
              - base
              - humidifier
            variables:
              sensors:
                - sensor.deerma_jsq5_cf89_relative_humidity
              circle_input: >
                [[[
                  if (entity) {
                    return entity.attributes.state == 'on' ?
                      entity.attributes.humidifier_target_humidity :
                      entity.attributes['environment.relative_humidity'];
                  }
                ]]]

      #################################################
      #                                               #
      #                      CASA                     #
      #                                               #
      #################################################

      - type: grid
        title: Casa
        view_layout:
          grid-area: casa
        columns: 2
        cards:
          - type: custom:button-card
            entity: person.stefano
            triggers_update:
              - sensor.stefano_last_changed
            double_tap_action: !include popup/casa_stefano.yaml
            variables:
              retain: sensor.stefano_last_changed
            template:
              - person
              - circle

          - type: custom:button-card
            entity: person.lidia
            triggers_update:
              - sensor.lidia_last_changed
            double_tap_action: !include popup/casa_lidia.yaml
            variables:
              retain: sensor.lidia_last_changed
            template:
              - person
              - circle

          - type: custom:button-card
            entity: script.sto_uscendo
            name: Sto uscendo
            template:
              - base
              - icon_away

          - type: custom:button-card
            entity: script.sono_a_casa
            name: Casa
            template:
              - base
              - icon_home

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: horizontal-stack
        view_layout:
          grid-area: footer
        cards:
          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:nas"></ha-icon> NAS
            tap_action: !include popup/footer_nas.yaml
            triggers_update:
              - update.nas_dsm_update
              - sensor.nas_volume_1_status
              - binary_sensor.nas_security_status
              - sensor.disk_use_percent
            variables:
              notify: >
                [[[
                 let id = this._config.triggers_update;
                  if (id.every(e => states[e]))
                      return states[id[0]].state === 'on'
                          ? 1
                          : states[id[1]].state === 'background_scrubbing' ||
                            states[id[2]].state === 'on' ||
                            parseFloat(states[id[3]].state) >= 85;
                ]]]
            template: footer

          - type: custom:button-card
            entity: sensor.template_updates
            name: >
              <ha-icon icon="mdi:arrow-up-bold-circle-outline"></ha-icon> Aggiornamenti
            tap_action: !include popup/footer_updates.yaml
            variables:
              notify: >
                [[[
                  return parseInt(entity?.state);
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:robot-vacuum"></ha-icon> Pulizia
            tap_action: !include popup/footer_vacuum.yaml
            triggers_update:
              - sensor.date
            variables:
              notify: >
                [[[
                  let id = states['sensor.morty_last_clean_end'];
                  if (id) return (Date.now() - Date.parse(id.state)) > 6048e5;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:chart-line-variant"></ha-icon> Storico
            tap_action: !include popup/footer_history.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:raspberry-pi"></ha-icon> Rpi
            tap_action: !include popup/footer_rpi.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:tablet"></ha-icon> Tablet
            tap_action: !include popup/footer_tablet.yaml
            variables:
              notify: >
                [[[
                  let id = states['binary_sensor.fire_tablet_fksa_is_charging'];
                  let level = states['sensor.fire_tablet_battery'];
                  if (id) return id.state === 'off' && parseInt(level.state) < 20;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:router-wireless"></ha-icon> Router
            tap_action: !include popup/footer_router.yaml
            double_tap_action: !include popup/footer_wifi_qr.yaml
            triggers_update:
              - update.unifi_dream_machine
              - binary_sensor.template_udm_internet
            variables:
              notify: >
                [[[
                  let id = this._config.triggers_update;
                  if (id.every(e => states[e]))
                      return states[id[0]].state === 'on'
                          ? 1
                          : states[id[1]].state === 'off';
                ]]]
            template: footer
