homeassistant:
  customize:
    fan.stylish_fan_only:
      friendly_name: Ventilatore camera

fan:
  - platform: template
    fans:
      stylish_fan_only:
        unique_id: stylish_fan_only
        speed_count: 3
        value_template: >
          {{ 'on' if is_state('climate.daikin_stylish', 'fan_only') else 'off' }}
        turn_on:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.daikin_stylish
            data:
              hvac_mode: fan_only
        turn_off:
          - service: climate.turn_off
            target:
              entity_id: climate.daikin_stylish
        percentage_template: >
          {% set speed = state_attr('climate.daikin_stylish', 'fan_mode') %}
          {% if speed == 'Auto' %}
            33
          {% elif speed == 'Silence' %}
            10
          {% else %}
            {{ (speed | float(default=0)) * 20 }}
          {% endif %}
        set_percentage:
          - service: climate.set_fan_mode
            target:
              entity_id: climate.daikin_stylish
            data:
              fan_mode: >
                {% if percentage <= 10 %}
                  Silence
                {% elif percentage == 33 %}
                  Auto
                {% else  %}
                  {{ (percentage / 20) | round(1) }}
                {% endif %}
          - condition: state
            entity_id: climate.daikin_stylish
            state: "off"
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.daikin_stylish
            data:
              hvac_mode: fan_only
        oscillating_template: >
          {{ is_state_attr('climate.daikin_stylish', 'swing_modes', 'off') == false }}
        set_oscillating:
          - service: climate.set_swing_mode
            target:
              entity_id: climate.daikin_stylish
            data:
              swing_mode: >
                {{ '3D' if is_state_attr('climate.daikin_stylish', 'swing_modes', 'Off') else 'Off'}}
