homeassistant:
  customize:
    sensor.diskstation_volume_1_average_disk_temp:
      friendly_name: Temperatura

sensor:
  # https://github.com/NemesisRE/sensor.plex_recently_added
  - platform: plex_recently_added
    host: !secret plex_host
    port: !secret plex_port
    token: !secret plex_token
    ssl: true
    max: 1
    img_dir: /
    scan_interval: 3600
    image_resolution: 800

# binary_sensor:
#   - platform: ping
#     name: nas_internet_access
#     host: 8.8.8.8

template:
  - sensor:
      - unique_id: nas_status
        state: >
          {% set entity_id = 'sensor.diskstation_volume_1_status' %}
          {% if is_state(entity_id, 'normal') %}
            Buono
          {% elif is_state(entity_id, 'background') %}
            Verifica
          {% else %}
            {{ states(entity_id) }}
          {% endif %}
        attributes:
          friendly_name: Integrità del sistema
          icon: cil:synology-nas

      - unique_id: domain_counter
        state: >
          {{ states | count }}
        attributes:
          automation: >
            {{ states.automation | count }}
          binary_sensor: >
            {{ states.binary_sensor | count }}
          device_tracker: >
            {{ states.device_tracker | count }}
          light: >
            {{ states.light | count }}
          media_player: >
            {{ states.media_player | count }}
          sensor: >
            {{ states.sensor | count }}
          switch: >
            {{ states.switch | count }}
          other: >
            {% set exclude = this.attributes | list %}
            {{ states | rejectattr('domain', 'in', exclude) | list | count }}
